### ISSUE TITLE
Feature request: preserve whitespace from templates

### ISSUE THREAD

**Issue by dtamai** [vicentebolea/bash-templater#4]
Hi! Thanks for this awesome script!

I'm using bash-templater to generate YAML files, so the spacing is relevant. I made a small change in the script to achieve this, configuring **IFS** as an empty string for the `read` command:

```bash
# ...

IFS='' # addition
while read -r line
# ...
```

And it works as expected.

@vicentebolea, does it make sense to have this feature in templater?

**Comment by vicentebolea** [comment]
@dtamai Thanks for taking the time to report this.

I think that I addressed it at #5. I wonder if you could check that branch. 

Thanks! :)

**Comment by dtamai** [comment]
Thanks for the quick response!

Yes, that resolves the issue for YAML files!
